export interface Localization {
	SquadType: SquadType;
	BulletType: BulletType;
	ArmorType: ArmorType;
	ArmorTypeLong: ArmorType;
	TacticRole: TacticRole;
	School: { [key: string]: string };
	AdaptationType: AdaptationType;
	SchoolLong: { [key: string]: string };
	Club: Club;
	BossFaction: BossFaction;
	Stat: { [key: string]: string };
	StatTooltip: StatTooltip;
	SkillType: SkillType;
	SkillTypeShort: SkillType;
	IsLimited: { [key: string]: string };
	FurnitureTemplate: { [key: string]: string };
	FurnitureSet: { [key: string]: string };
	ItemCategory: ItemCategory;
	ArtifactClass: { [key: string]: string };
	CharacterSize: CharacterSize;
	EventName: { [key: string]: string };
	StageType: StageType;
	TimeAttackStage: TimeAttackStage;
	ConquestMap: { [key: string]: string };
	StageTitle: StageTitle;
	EnemyRank: EnemyRank;
	NodeQuality: { [key: string]: string };
	NodeTier: { [key: string]: string };
	RaidDifficulty: RAIDDifficulty;
	WeaponPartExpBonus: WeaponPartExpBonus;
	BuffType: BuffType;
	BuffName: { [key: string]: string };
	BuffNameLong: { [key: string]: string };
	BuffTooltip: { [key: string]: string };
	ServerName: { [key: string]: string };
	ShopCategory: ShopCategory;
	GroggyCondition: GroggyCondition;
	RaidChangePhase: RAIDChangePhase;
	VoiceClipGroup: VoiceClipGroup;
	VoiceClip: { [key: string]: string };
	Shortcut: Shortcut;
	InteractionType: { [key: string]: string };
	InteractionTypeDescription: { [key: string]: string };
	UI: UI;
	BGM: { [key: string]: string };
}

export interface AdaptationType {
	Street: string;
	Outdoor: string;
	Indoor: string;
}

export interface ArmorType {
	LightArmor: string;
	HeavyArmor: string;
	Unarmed: string;
	ElasticArmor: string;
	Normal: string;
	Structure: string;
	Mixed?: string;
}

export interface BossFaction {
	Decagrammaton: string;
	Slumpia: string;
	CommunioSanctorum: string;
	Kaitenger: string;
	TheLibraryofLore: string;
	SevenPrisoners: string;
	HundredGhostTales: string;
}

export interface BuffType {
	Buff: string;
	Debuff: string;
	CC: string;
	Special: string;
}

export interface BulletType {
	Explosion: string;
	Pierce: string;
	Mystic: string;
	Normal: string;
	Sonic: string;
	Mixed: string;
}

export interface CharacterSize {
	Small: string;
	Medium: string;
	Large: string;
	XLarge: string;
}

export interface Club {
	Kohshinjo68: string;
	Justice: string;
	CleanNClearing: string;
	BookClub: string;
	Countermeasure: string;
	Engineer: string;
	FoodService: string;
	Fuuki: string;
	GourmetClub: string;
	HoukagoDessert: string;
	KnightsHospitaller: string;
	MatsuriOffice: string;
	Meihuayuan: string;
	Onmyobu: string;
	RemedialClass: string;
	SPTF: string;
	Shugyobu: string;
	Endanbou: string;
	TheSeminar: string;
	TrainingClub: string;
	TrinityVigilance: string;
	Veritas: string;
	NinpoKenkyubu: string;
	GameDev: string;
	RedwinterSecretary: string;
	anzenkyoku: string;
	SisterHood: string;
	Class227: string;
	Emergentology: string;
	RabbitPlatoon: string;
	PandemoniumSociety: string;
	AriusSqud: string;
	HotSpringsDepartment: string;
	TeaParty: string;
	PublicPeaceBureau: string;
	BlackTortoisePromenade: string;
	Genryumon: string;
	LaborParty: string;
	KnowledgeLiberationFront: string;
	Hyakkayouran: string;
	ShinySparkleSociety: string;
	AbydosStudentCouncil: string;
	EmptyClub: string;
}

export interface EnemyRank {
	Champion: string;
	Elite: string;
	Minion: string;
	Summoned: string;
}

export interface GroggyCondition {
	TypeDamage: string;
	Chesed: string;
	ShiroKuro: string;
	Hieronymus: string;
	KaitenFxMk0: string;
	Perorozilla: string;
	HOD: string;
	HoverCraft: string;
	EN0005: string;
}

export interface ItemCategory {
	Furnitures: string;
	Decorations: string;
	Interiors: string;
	Wallpaper: string;
	Floor: string;
	Background: string;
	Table: string;
	Chair: string;
	Closet: string;
	FloorDecoration: string;
	WallDecoration: string;
	Prop: string;
	HomeAppliance: string;
	FurnitureEtc: string;
	Bed: string;
	Material: string;
	SecretStone: string;
	Favor: string;
	CharacterExpGrowth: string;
	Coin: string;
	Equipment: string;
	Currency: string;
	Consumable: string;
	Collectible: string;
	Exp: string;
	WeaponExpGrowth: string;
	WeaponExpGrowthA: string;
	WeaponExpGrowthB: string;
	WeaponExpGrowthC: string;
	WeaponExpGrowthZ: string;
	Box: string;
	Hat: string;
	Gloves: string;
	Shoes: string;
	Bag: string;
	Badge: string;
	Hairpin: string;
	Charm: string;
	Necklace: string;
	Watch: string;
	Artifact: string;
	BookItem: string;
	CDItem: string;
}

export interface RAIDChangePhase {
	HPUnder: string;
}

export interface RAIDDifficulty {
	Normal: string;
	Hard: string;
	VeryHard: string;
	HardCore: string;
	Extreme: string;
	Insane: string;
	Torment: string;
	A: string;
	B: string;
	C: string;
}

export interface ShopCategory {
	General: string;
	Raid: string;
	SecretStone: string;
	SecretStoneGrowth: string;
	Arena: string;
	TimeAttack: string;
	MasterCoin: string;
	Chaser: string;
	EliminateRaid: string;
}

export interface Shortcut {
	Students: string;
	Calculator: string;
	Raids: string;
	Items: string;
	Stages: string;
	Crafting: string;
}

export interface SkillType {
	Normal: string;
	Ex: string;
	Public: string;
	GearPublic: string;
	Passive: string;
	WeaponPassive: string;
	ExtraPassive: string;
}

export interface SquadType {
	Main: string;
	Support: string;
}

export interface StageTitle {
	ChaserA: string;
	ChaserB: string;
	ChaserC: string;
	Blood: string;
	FindGift: string;
	SchoolA: string;
	SchoolB: string;
	SchoolC: string;
}

export interface StageType {
	Campaign: string;
	Bounty: string;
	WeekDungeon: string;
	SchoolDungeon: string;
	Event: string;
	Raid: string;
	Arena: string;
	TimeAttack: string;
	WorldRaid: string;
	ChaserA: string;
	ChaserB: string;
	ChaserC: string;
	Blood: string;
	FindGift: string;
	SchoolA: string;
	SchoolB: string;
	SchoolC: string;
	Conquest: string;
	EliminateRaid: string;
	MultiFloorRaid: string;
	Normal: string;
	Hard: string;
	Quest: string;
	Story: string;
	Challenge: string;
	Field: string;
}

export interface StatTooltip {
	MaxHP: string;
	AttackPower: string;
	DefensePower: string;
	HealPower: string;
	AccuracyPoint: string;
	DodgePoint: string;
	CriticalPoint: string;
	CriticalDamageRate: string;
	HealEffectivenessRate: string;
	OppressionPower: string;
	OppressionResist: string;
	CriticalChanceResistPoint: string;
	CriticalDamageResistRate: string;
	StabilityPoint: string;
	StabilityRate: string;
	Range: string;
	AmmoCount: string;
	MoveSpeed: string;
	DamageRatio: string;
	DamagedRatio: string;
	ExDamagedRatio: string;
	AttackSpeed: string;
	BlockRate: string;
	DefensePenetration: string;
	RegenCost: string;
	EnhanceExplosionRate: string;
	EnhancePierceRate: string;
	EnhanceMysticRate: string;
	EnhanceSonicRate: string;
	ExtendBuffDuration: string;
	ExtendDebuffDuration: string;
	ExtendCrowdControlDuration: string;
}

export interface TacticRole {
	DamageDealer: string;
	Tanker: string;
	Healer: string;
	Supporter: string;
	Vehicle: string;
}

export interface TimeAttackStage {
	Shooting: string;
	Defense: string;
	Destruction: string;
	Escort: string;
}

export interface VoiceClipGroup {
	Normal: string;
	Battle: string;
	Lobby: string;
	Event: string;
}

export interface WeaponPartExpBonus {
	WeaponExpGrowthA: string;
	WeaponExpGrowthB: string;
	WeaponExpGrowthC: string;
	WeaponExpGrowthZ: string;
}

export interface UI {
	navbar_home: string;
	students: string;
	student: string;
	enemy: string;
	stages: string;
	events: string;
	raids: string;
	crafting: string;
	tools: string;
	damage_calculator: string;
	student_compare: string;
	synthesis: string;
	fusion: string;
	shops: string;
	schedule: string;
	event_stages: string;
	event_shop: string;
	item_sources: string;
	item_usage: string;
	item: string;
	settings: string;
	settings_appearance: string;
	settings_server: string;
	settings_server_description: string;
	settings_language: string;
	settings_language_description: string;
	settings_theme: string;
	settings_theme_description: string;
	settings_contrast: string;
	settings_contrast_description: string;
	settings_experiments: string;
	settings_preferences: string;
	settings_itemids: string;
	settings_itemids_description: string;
	settings_distanceunit: string;
	settings_distanceunit_description: string;
	settings_animationunit: string;
	settings_animationunit_description: string;
	settings_animation: string;
	settings_animation_description: string;
	settings_data: string;
	settings_servercollection: string;
	settings_servercollection_description: string;
	settings_collection: string;
	settings_collection_description: string;
	settings_restorepage: string;
	settings_restorepage_description: string;
	settings_defaultpage: string;
	settings_defaultpage_description: string;
	settings_showskilldelay: string;
	settings_showskilldelay_description: string;
	settings_screenmode: string;
	settings_screenmode_description: string;
	search: string;
	filter_by_name: string;
	collection_export_collection: string;
	collection_import_collection: string;
	collection_import_help: string;
	collection_import_warning: string;
	collection_import_status_valid: string;
	collection_import_status_invalid: string;
	collection_export_placeholder: string;
	collection_import_placeholder: string;
	collection_export: string;
	collection_import: string;
	setting_off: string;
	setting_on: string;
	setting_open: string;
	setting_normal: string;
	setting_slow: string;
	setting_metric: string;
	setting_raw: string;
	setting_seconds: string;
	setting_frames: string;
	setting_lastviewed: string;
	current_events: string;
	server_region: string;
	server_reset_in: string;
	home_timezone: string;
	event_starts: string;
	event_ends: string;
	duration_days: string;
	duration_hours: string;
	duration_minutes: string;
	student_birthdays: string;
	attributes: string;
	stats: string;
	sort_order: string;
	base_stats: string;
	max_stats: string;
	collection_stats: string;
	sp_sub_skill: string;
	skills: string;
	ex_weapon: string;
	ex_gear: string;
	profile: string;
	voice: string;
	student_gear_short: string;
	student_weapon: string;
	student_gear: string;
	student_ex_gear: string;
	student_bond: string;
	student_potential: string;
	support_stats: string;
	special_students: string;
	add_recommended: string;
	buff_search: string;
	no_compatible_effects: string;
	buff_overwritten: string;
	filter_all: string;
	filter_bookmark: string;
	buff_custom_add: string;
	buff_custom: string;
	buff_custom_base: string;
	buff_custom_coefficient: string;
	buff_custom_name_placeholder: string;
	buff_custom_value_placeholder: string;
	student_skills_upgrades: string;
	student_skills_materials: string;
	student_skills_materials_none: string;
	student_weapon_rank_2star_desc: string;
	student_weapon_rank_3star_desc: string;
	student_gear_t2_desc: string;
	attack_type_desc: string;
	attack_type_normal_desc: string;
	defense_type_desc: string;
	defense_type_normal_desc: string;
	comfort: string;
	age: string;
	birthday: string;
	hobbies: string;
	height: string;
	cv: string;
	designer: string;
	illustrator: string;
	bond_title: string;
	potential_title: string;
	favoritem_title: string;
	favoritem_none: string;
	furniture_title: string;
	furniture_none: string;
	student_list: string;
	list: string;
	filters: string;
	filters_clear: string;
	students_displayed: string;
	student_search_info: string;
	sortby: string;
	default: string;
	release_date: string;
	stat: string;
	name: string;
	type: string;
	role: string;
	rarity: string;
	rarity_availability: string;
	attacktype: string;
	defensetype: string;
	school: string;
	club: string;
	weapon: string;
	position: string;
	category: string;
	subcategory: string;
	combat_power: string;
	misc: string;
	uses_cover: string;
	doesnt_use_cover: string;
	can_cc: string;
	can_buff: string;
	can_debuff: string;
	can_heal: string;
	can_shield: string;
	can_dispel: string;
	can_reposition: string;
	can_summon: string;
	ex_ignore_cover: string;
	ex_area_damage: string;
	uses_artifact: string;
	filter_include_weapon_upgrade: string;
	memory_lobby: string;
	memory_lobby_student: string;
	memory_lobby_unlock: string;
	memory_lobby_unlock_level: string;
	memory_lobby_bgm_name: string;
	student_stars: string;
	terrain_adaption: string;
	terrain_adaption_details: string;
	stat_details: string;
	buffs: string;
	configure_buffs: string;
	self: string;
	ally: string;
	target: string;
	summon: string;
	summon_inheritance: string;
	damage_reduction: string;
	minimum_damage: string;
	striker_bonus: string;
	stat_info: string;
	rec_level: string;
	stage_rewards: string;
	rewards_none: string;
	rewards_findgift_msg: string;
	stage_enemies: string;
	stage_info: string;
	stage_map: string;
	stage_conquest_tile: string;
	event_version: string;
	stage_original: string;
	stage_rerun: string;
	stage_permanent: string;
	starcondition_clear: string;
	starcondition_cleartime: string;
	starcondition_earnrewards: string;
	starcondition_defeatall: string;
	starcondition_defeatalltime: string;
	starcondition_allsurvive: string;
	starcondition_complete: string;
	starcondition_clearturns: string;
	starcondition_sranks: string;
	no_results: string;
	furniture_set: string;
	furniture_template: string;
	furniture_templates: string;
	furniture_size: string;
	others: string;
	options: string;
	details: string;
	calculations: string;
	options_short: string;
	rules: string;
	ta_phase: string;
	craft_rewards: string;
	craft_fusion: string;
	craft_recipe_items: string;
	craft_using: string;
	craft_toggle_chance: string;
	craft_toggle_language: string;
	bond_req_equip: string;
	bond_req_upgrade: string;
	gacha_pickup: string;
	rewards: string;
	stage_reward_firstclear: string;
	stage_reward_threestar: string;
	stage_reward_bonus: string;
	no_bonus: string;
	max_bonus: string;
	own_bonus: string;
	max_bonus_amount: string;
	rewards_season: string;
	raid_tab: string;
	seasons: string;
	raid_season: string;
	raid_season_select: string;
	furniture: string;
	equipment: string;
	equipment_tier: string;
	show_all: string;
	craftable: string;
	stagedrop: string;
	shop: string;
	furniture_interaction_list: string;
	item_student_favor: string;
	item_student_favor_default: string;
	item_student_favor_all: string;
	item_usedby_gear: string;
	item_usedby_potential: string;
	item_usedby: string;
	item_usedby_exskill_amount: string;
	item_usedby_skill_amount: string;
	item_usedby_skill: string;
	item_usedby_eleph: string;
	item_usedby_none: string;
	item_obtainedfrom_stage: string;
	item_obtainedfrom_synthesis: string;
	synthesis_ingredients: string;
	random_item: string;
	group_tooltip_overflow: string;
	ingredient_list: string;
	item_obtainedfrom_fusion: string;
	item_obtainedfrom_consumable: string;
	item_purchasedfrom: string;
	item_eventbonus: string;
	item_contains: string;
	item_contains_random: string;
	item_contains_choice: string;
	conquest_area: string;
	conquest_occupy: string;
	conquest_operate: string;
	conquest_analyze: string;
	base_level: string;
	base_upgrade_cost: string;
	base_settlement: string;
	school_bonus: string;
	school_bonus_num_students: string;
	school_bonus_conquest: string;
	tooltip_bond_level: string;
	tooltip_weapon_level: string;
	tooltip_potential_level: string;
	tooltip_collection_add: string;
	tooltip_collection_remove: string;
	tooltip_sprite_toggle: string;
	collection: string;
	collection_owned: string;
	collection_notowned: string;
	favourites: string;
	favourites_add: string;
	favourites_remove: string;
	add: string;
	remove: string;
	toast_import_success: string;
	toast_import_failure: string;
	toast_import_copy: string;
	toast_amount_invalid: string;
	toast_release_warning: string;
	stat_defense_tooltip: string;
	stat_crit_tooltip: string;
	stat_crit_amount_tooltip: string;
	stat_stability_tooltip: string;
	home_header: string;
	home_change_server: string;
	home_copyright: string;
	changelog: string;
	about: string;
	links: string;
	community_resources: string;
	skillinfo_empty: string;
	skill_normalattack_target: string;
	skill_normalattack_circle: string;
	skill_normalattack_line: string;
	skill_normalattack_fan: string;
	type_effectiveness: string;
	level_difference: string;
	hit_rate: string;
	crit_rate: string;
	block_rate: string;
	dmginfo_ignore_def: string;
	dmginfo_hit_avg: string;
	dmginfo_total_avg: string;
	dmginfo_dmg: string;
	dmginfo_heal: string;
	dmginfo_dmg_avg: string;
	dmginfo_minimum: string;
	dmginfo_maximum: string;
	dmginfo_nocrit_avg: string;
	dmginfo_allcrit_avg: string;
	rate_of_fire: string;
	attacks_per_min: string;
	attacks_per_min_tooltip: string;
	time_seconds: string;
	time_frames: string;
	time_seconds_frames: string;
	dmginfo_avg_dps: string;
	dmginfo_heal_amount: string;
	dmginfo_shield_amount: string;
	dmginfo_cc_effect_chance: string;
	dmginfo_duration: string;
	dmginfo_accumulation_limit: string;
	peroro_target_1: string;
	peroro_target_2: string;
	peroro_target_3: string;
	voicegallery: string;
	skill_target_hp: string;
	max_attributes: string;
	lock_attributes: string;
	lock_attributes_help: string;
	midokuni_link: string;
	version_lastupdated: string;
	info_unavailable: string;
	range: string;
	radius: string;
	angle: string;
	length: string;
	width: string;
	bounce: string;
	skill_duration: string;
	skill_delay: string;
	tsa_board: string;
	tooltip_combat_style: string;
	show_cumulative: string;
	exp_value: string;
	exp_bonus: string;
	craft_quality: string;
	shifting_craft_quality: string;
	unit_clear_map_filter: string;
	gachagroup_contents: string;
	base_chance: string;
	appearance_rate: string;
	appearance_rate_help: string;
	avg_damage_help: string;
	cc_gauge_fill: string;
	cc_gauge_fill_help: string;
	effect_shiro_bomb: string;
	effect_shiro_icebomb: string;
	effect_shiro_stickybomb: string;
	avg_dps_help: string;
	frames_attackenter: string;
	frames_attackenter_help: string;
	frames_attackready: string;
	frames_attackready_help: string;
	frames_attacking: string;
	frames_attacking_help: string;
	frames_attackreload: string;
	frames_attackreload_help: string;
	frames_attackstart: string;
	frames_attackstart_help: string;
	frames_attackburstroundover: string;
	frames_attackburstroundover_help: string;
	ignore_delay: string;
	ignore_delay_help: string;
	select_all: string;
	select_student: string;
	select_target: string;
	select_special: string;
	calculation_result: string;
	configure_columns: string;
	critical: string;
	damage_hit: string;
	damage_hits: string;
	damage_ticks: string;
	ignores_cover: string;
	ignores_cover_partial: string;
	unavoidable: string;
	always_critical: string;
	never_critical: string;
	student_unique_short: string;
	student_event_short: string;
	student_fest_short: string;
	selection_selected: string;
	selection_confirm: string;
	selection_clear: string;
	buff_effects: string;
	base_value: string;
	character_size: string;
	enemy_rank: string;
	difficulty: string;
	event_bonus: string;
	group_view: string;
	skill_related: string;
	purchase_per_day: string;
	purchase_per_month: string;
	distance_units: string;
	date_today: string;
	num_alts: string;
}
